# Based on igbinary and php-ast's appveyor config.
# The project name is the same as the build id used, e.g. https://www.appveyor.com/docs/environment-variables/

version: '{branch}.{build}'
clone_folder: C:\projects\php-parser-to-php-ast
# Don't include full git history
clone_depth: 1
# Test 32-bit builds
platform: x86

branches:
  only:
    - master
    - 0.8
    - 0.9
    - php72

install:
- cmd: choco feature enable -n=allowGlobalConfirmation
- cmd: mkdir %APPVEYOR_BUILD_FOLDER%\bin
build_script:
- cmd: >-
    mkdir C:\projects\php

    cd C:\projects\php

    SET PHP_ZIP_BASENAME=php-7.1.33-nts-Win32-VC14-x86.zip

    SET PHP_AST_VERSION=0.1.6
    SET AST_ZIP_BASENAME=php_ast-%PHP_AST_VERSION%-7.1-nts-vc14-x86.zip

    curl -fsS https://windows.php.net/downloads/releases/archives/%PHP_ZIP_BASENAME% -o %PHP_ZIP_BASENAME% || curl -fsS https://windows.php.net/downloads/releases/%PHP_ZIP_BASENAME% -o %PHP_ZIP_BASENAME%

    7z x -y %PHP_ZIP_BASENAME%

    del /Q *.zip

    cd C:\projects\php\ext

    curl -fsS https://windows.php.net/downloads/pecl/releases/ast/%PHP_AST_VERSION%/%AST_ZIP_BASENAME% -o %AST_ZIP_BASENAME%

    7z x %AST_ZIP_BASENAME% php_ast.dll -y >nul

    cd C:\projects\php

    echo [PHP] > php.ini

    echo extension_dir = "ext" >> php.ini

    echo extension=php_ast.dll >> php.ini

    echo extension=php_curl.dll >> php.ini

    echo extension=php_intl.dll >> php.ini

    echo extension=php_mbstring.dll >> php.ini

    echo extension=php_openssl.dll >> php.ini

    echo extension=php_soap.dll >> php.ini

    SET PATH=c:\projects\php;%PATH%

    echo %PATH%

    php -v

    php -m

    cd C:\projects\php-parser-to-php-ast

    appveyor DownloadFile https://getcomposer.org/composer.phar

test_script:
- cmd: cd C:\projects\php-parser-to-php-ast
- cmd: php composer.phar install
# Analyze the project with phan, will error if 1 or more issues are detected
#- cmd: .\vendor\bin\phan # requires newer php-ast
# Run the remaining tests of this project
- cmd: .\vendor\bin\phpunit --verbose
